# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SPRITELAB
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arturtabiszewski.github.io" # the base hostname & protocol for your site
twitter_username: spritelabtwitter
github_username:  jekyll

# Build settings
markdown: kramdown

highlighter: rouge


prose:
  rooturl: '_posts'
  siteurl: 'http://arturtabiszewski.github.io/'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
          value: ""
      - name: "date"
        field: 
          element: "hidden"
          label: "date"
          value: CURRENT_DATETIME
      - name: "categories"
        field:
          element: "hidden"
          label: "categories"
          value: "jekyll update"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Java"
              value: "java"
            - name: "libGDX"
              value: "libgdx"
            - name: "Code"
              value: "code"
            - name: "GameArt"
              value: "gameart"
